GET https://jsonplaceholder.typicode.com/posts
Accept: application/json

###

GET https://jsonplaceholder.typicode.com/comments
Accept: application/json

###

GET https://jsonplaceholder.typicode.com/albums
Accept: application/json

###

GET https://jsonplaceholder.typicode.com/photos
Accept: application/json

###

GET https://jsonplaceholder.typicode.com/todos
Accept: application/json

###

GET https://jsonplaceholder.typicode.com/users
Accept: application/json

###


